In [4]:
import numpy as np

In [5]:
def Ver001(x):
    return [1/(1 + np.exp(-ele)) for ele in x]

def Ver002(x):
    return 1 / (1 + (np.exp(-x)))

min_limit = 709
def Ver003(x):
    return 1 / (1 + np.exp(-(np.clip(x,-min_limit,None))))

In [6]:
Ver001([1])

[0.7310585786300049]

In [10]:
Ver002(0)

0.5

In [7]:
Ver003([1])

array([0.73105858])

Convert a given numpy array to its sigmoid and its associated derivative

In [24]:
# input array
x = [[3, 1], [0, 4]] 

#Sample output
# [[0.95 0.73]
#  [0.5 0.98]] 
# [[0.05 0.2 ]
#  [0.25 0.02]]

In [25]:
import numpy as np
import warnings as war
war.filterwarnings('ignore')

def sigmoid(x):
    '''x is a list
       Output -> Two numpy arrays are expected to be returned both with the same dimensions as of x'''
    
    x = np.asarray(x)

    sigmoid  = 1 / (1 + (np.exp(-x)))
    sigmoid_dev = sigmoid * (1 - sigmoid)
    print(sigmoid.round(2))
    print(sigmoid_dev.round(2))
           
#Driver function
sigmoid(x)

[[0.95 0.73]
 [0.5  0.98]]
[[0.05 0.2 ]
 [0.25 0.02]]


Q) Log loss and derivative


Problem Statement

LogLoss is defined as: −y.log( 
y
​
 )−(1−y).log(1− 
y
​
 ),
where y represents the true label and  
y
​
  represents the probability output by logistic regression model.


Problem Description:

Given the true labels for the ith sample is y 
i
​
  and z 
i
​
 =w 
0
​
 +∑ 
j=1
d
​
 w 
j
​
 ×x 
ij
​
 , where:

1. d is the number of features used

2. w 
j
​
  is the jth value of the weight of the model

3. x 
ij
​
  is the jth feature value of the ith sample



Find and return the logLoss and the derivative of logLoss (w.r.t to the first feature) which is defined as:



dwj/dL(w)  =(yi − yi))*(−xij)



Note: The values in the arrays should be rounded up to 2 decimals.

In [26]:
# input
z = [3.11, 0.08, 0.76, 5.98, 3.05, 0.12, 8.99, 1.69, 1.75, 1.54] 
y_true = [1, 0, 1, 0, 0, 0, 1, 1, 0, 1]  
x = [[11, 22], [39, 0], [33, 39], [1, 28], [9, 24], [19, 14], [6, 7], [28, 3], [4, 17], [35, 15]]

In [54]:
import numpy as np
def logloss(z, y_true, x):
    '''z, y_true and x are lists
       output -> Two numpy arrays are expected to be returned'''
    
    z = np.asarray(z)
    y_true = np.asarray(y_true)
    x = np.asarray(x)
    
    # YOUR CODE GOES HERE

    y_hat = 1 / (1 + (np.exp(-z)))
    #y_hat = y_hat.round(2)

    logloss = (-1 * y_true * np.log(y_hat)) - ((1 - y_true) * np.log(1 - y_hat))
    logloss = logloss.round(2)
    
    logloss_dev = (y_hat - y_true) * [x[0] for x in x]
    logloss_dev = logloss_dev.round(2)

    return logloss,logloss_dev



logloss(z, y_true, x)

(array([0.04, 0.73, 0.38, 5.98, 3.1 , 0.75, 0.  , 0.17, 1.91, 0.19]),
 array([ -0.47,  20.28, -10.52,   1.  ,   8.59,  10.07,  -0.  ,  -4.36,
          3.41,  -6.18]))

In [53]:
[x[0] for x in x]

[11, 39, 33, 1, 9, 19, 6, 28, 4, 35]

In [55]:
x[:,0]

TypeError: list indices must be integers or slices, not tuple

**Problem Description**

Given train and test data in the form of lists as arguments of the function errors(), complete the function to return the lists train_errs and test_errs where train_err will consist of the errors in X_train for different values of C in the list c, and test_errs will have the errors for the test data.
 - ***C is basically a hyperparameter in the logistic regression model representing the reciprocal of regularization parameter λ. High values of C cause less regularization which leads the model to overfit on training data, whereas low values of C causes it to underfit.***

Note: Here, by error we mean the percentage of misclassified points, converted to decimal.


Sample Input:

- X_train = [[93, 17], [83, 8], [80, 13], [15, 30], [63, 31], [11, 28], [73, 55], [82, 11], [50, 6], [2, 89]]
- y_train = [0, 0, 1, 0, 1, 1, 1, 1, 0, 1]
- X_test = [[9, 53], [6, 7], [21, 61], [65, 75], [48, 67]]
- y_test = [0, 0, 1, 0, 0]
- c = [0.001, 0.01, 0.1, 1, 10, 100, 1000]


Sample Output:

- train_errs = [0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
- test_errs = [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]

In [74]:
import numpy as np

#import logistic regression
from sklearn.linear_model import LogisticRegression

def training_errors(X_train, y_train, X_test, y_test,c):
    ''' X_train, y_train, X_test, y_test,c are all in the form of lists
        Output -> Two lists are expected to be returned'''
    
    #converting all the lists into Numpy arrays
    X_train = np.asarray(X_train)  
    X_test = np.asarray(X_test)  
    y_train = np.asarray(y_train)  
    y_test = np.asarray(y_test)  
    train_errs = list()
    test_errs = list()
    
    for c_value in c:
        #initialize the logistic regression model
        clf = LogisticRegression(C=c_value)
        
        #fit the training data on the model
        clf.fit(X_train,y_train)

        #y_pred_train = clf.predict(X_train)
        train_score = clf.score(X_train,y_train)
        test_score = clf.score(X_test,y_test)
        
        #append the errors for each value of C for train and test data.
        train_errs.append(round( 1.0 - train_score, 2))
        test_errs.append(round( 1.0 - test_score,2))
    
    return train_errs,test_errs

In [75]:
X_train = [[44, 15],[75, 17],[30, 50],[41, 89],[15,3],[36,  7],[46, 22],[96, 13],[85,  5],[81, 35]]
y_train = [1, 1, 1, 0, 1, 1, 0, 1, 0, 0]
X_test = [[61, 64],[40, 91],[67, 22],[81, 13],[50, 85],[30, 49],[35, 10],[49, 76],[50, 65],[56,  2]]
y_test = [0, 1, 0, 0, 1, 0, 0, 0, 0, 1]
c = [0.001, 0.01, 0.1, 1, 10, 100, 1000]


training_errors(X_train, y_train, X_test, y_test,c)

([0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3], [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6])

Q6. Train and predict

Problem Description

Given the fixed acidity, volatile acidity, and residual sugar levels of certain wine samples, predict whether these wine samples are of good or bad quality (Good being y=1 and bad being y=0). Complete the function predict_class(), using the X_train, y_train, and X_test for returning the predictions of wine samples in the X_test.

Instructions:
1. Import the logistic regression model
2. Train the Logistic Regression model on the training data.
3. Predict the classes of the observations present in the test data (X_test).
4. Return the NumPy array of predictions.

In [76]:
X_train = [[44, 20, 5], [53, 44, 42], [71, 82, 18], [84, 67, 69], [79, 55, 1], [5, 97, 79], [73, 51, 60], [95, 45, 69], [79, 3, 64], [56, 94, 50], [32, 60, 74], [21, 54, 23], [72, 1, 22], [96, 4, 92], [98, 74, 3]]
y_train = [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1]
X_test = [[94, 31, 74], [7, 48, 18], [19, 67, 18], [30, 88, 1], [87, 35, 36]]

In [77]:
import numpy as np
# import logistic regression model
from sklearn.linear_model import LogisticRegression

def predict_class(X_train, y_train, X_test):
    '''X_train, y_train, X_test are all in the form of lists
       Output -> A numpy array of class labels of the same length as of X_test is expected to be returned'''
    
    X_train = np.asarray(X_train)
    y_train = np.asarray(y_train)
    X_test = np.asarray(X_test)
    
    #initialize the logistic regression model
    clf = LogisticRegression()
    
    #fit the training data on the model
    clf.fit(X_train,y_train)  
    
    #predict the labels of the observations in X_test
    predictions = clf.predict(X_test)  
    return predictions

In [78]:
predict_class(X_train, y_train, X_test)

array([0, 1, 0, 1, 0])

Q7. Metrics-Accuracy

Problem Description:

Create a function that calculates accuracy for the given input arrays.

Accuracy=  
TotalPrediction
CorrectPrediction

Note: After Calculating the accuracy, multiply accuracy with 100 and print the output.
Do not Use Scikit Learn Functions

In [80]:
actual = [1,0,2]
predicted = [1,0,1]

In [96]:
import numpy as np

def accuracy_metric(actual, predicted):
    accuracy = 0
    
    # YOUR CODE GOES HERE
    count = 0

    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            count += 1
    
    accuracy = (count / len(actual)) * 100

    return accuracy
    

In [97]:
accuracy_metric(actual, predicted)

66.66666666666666

### Area Under the Curve

Calculate the AUC for the given inputs

- probab = [0.64, 0.01, 0.22, 0.44, 0.02, 0.64, 0.87, 0. , 0.06, 0.8 ]
- labels = [1, 0, 1, 1, 0, 0, 1, 1, 0, 0]

In [32]:
import pandas as pd
import numpy as np
def au_roc(prob, labels):
    
    data = pd.DataFrame({"probab" : prob, "y" : labels})
    
    #storing all the threshold values sorted in descending order
    thr=  list(set(data['probab']))
    thr.sort(reverse = True)
    
    tpr_arr,fpr_arr = [],[]

    for i in thr:
        #adding new column y_pred based on probability score and threshold
        data['y_pred'] = data['probab'].apply(lambda y_score: 0 if y_score < i else 1)
        
        #calculate true negatives, false positives, false negatives and true positives
        tn = len(data[(data.y == 0) & (data.y_pred == 0)])
        fp = len(data[(data.y== 0) & (data.y_pred == 1)])
        fn = len(data[(data.y == 1) & (data.y_pred == 0)])
        tp = len(data[(data.y == 1) & (data.y_pred == 1)])
        
        #calculate true positive rate and false positive rate
        tpr = tp/(tp + fn)
        fpr = fp/(tn + fp)
        
        tpr_arr.append(tpr)
        fpr_arr.append(fpr)

    
    #Calculating the area under curve using trapz function
    auroc = np.trapz(y = tpr_arr, x=fpr_arr)
    print('tpr_array: ',tpr_arr)
    print('fpr_array: ',fpr_arr)

    return auroc.round(2)

    

In [33]:
probab = [0.64, 0.01, 0.22, 0.44, 0.02, 0.64, 0.87, 0. , 0.06, 0.8 ]
#probab = np.sqrt(probab)
labels = [1, 0, 1, 1, 0, 0, 1, 1, 0, 0]

au_roc(probab, labels)

tpr_array:  [0.2, 0.2, 0.4, 0.6, 0.8, 0.8, 0.8, 0.8, 1.0]
fpr_array:  [0.0, 0.2, 0.4, 0.4, 0.4, 0.6, 0.8, 1.0, 1.0]


0.58

In [34]:
probab = [0.64, 0.01, 0.22, 0.44, 0.02, 0.64, 0.87, 0. , 0.06, 0.8 ]
probab = np.sqrt(probab)
labels = [1, 0, 1, 1, 0, 0, 1, 1, 0, 0]

au_roc(probab, labels)

tpr_array:  [0.2, 0.2, 0.4, 0.6, 0.8, 0.8, 0.8, 0.8, 1.0]
fpr_array:  [0.0, 0.2, 0.4, 0.4, 0.4, 0.6, 0.8, 1.0, 1.0]


0.58