In [1]:
import numpy as np

In [2]:
def Ver001(x):
    return [1/(1 + np.exp(-ele)) for ele in x]

def Ver002(x):
    return 1 / (1 + (np.exp(-x)))

min_limit = 709
def Ver003(x):
    return 1 / (1 + np.exp(-(np.clip(x,-min_limit,None))))

In [5]:
Ver001([1])

[0.7310585786300049]

In [8]:
Ver002(1)

0.7310585786300049

In [7]:
Ver003([1])

array([0.73105858])

Convert a given numpy array to its sigmoid and its associated derivative

In [24]:
# input array
x = [[3, 1], [0, 4]] 

#Sample output
# [[0.95 0.73]
#  [0.5 0.98]] 
# [[0.05 0.2 ]
#  [0.25 0.02]]

In [25]:
import numpy as np
import warnings as war
war.filterwarnings('ignore')

def sigmoid(x):
    '''x is a list
       Output -> Two numpy arrays are expected to be returned both with the same dimensions as of x'''
    
    x = np.asarray(x)

    sigmoid  = 1 / (1 + (np.exp(-x)))
    sigmoid_dev = sigmoid * (1 - sigmoid)
    print(sigmoid.round(2))
    print(sigmoid_dev.round(2))
           
#Driver function
sigmoid(x)

[[0.95 0.73]
 [0.5  0.98]]
[[0.05 0.2 ]
 [0.25 0.02]]


Q) Log loss and derivative


Problem Statement

LogLoss is defined as: −y.log( 
y
​
 )−(1−y).log(1− 
y
​
 ),
where y represents the true label and  
y
​
  represents the probability output by logistic regression model.


Problem Description:

Given the true labels for the ith sample is y 
i
​
  and z 
i
​
 =w 
0
​
 +∑ 
j=1
d
​
 w 
j
​
 ×x 
ij
​
 , where:

1. d is the number of features used

2. w 
j
​
  is the jth value of the weight of the model

3. x 
ij
​
  is the jth feature value of the ith sample



Find and return the logLoss and the derivative of logLoss (w.r.t to the first feature) which is defined as:



dwj/dL(w)  =(yi − yi))*(−xij)



Note: The values in the arrays should be rounded up to 2 decimals.

In [26]:
# input
z = [3.11, 0.08, 0.76, 5.98, 3.05, 0.12, 8.99, 1.69, 1.75, 1.54] 
y_true = [1, 0, 1, 0, 0, 0, 1, 1, 0, 1]  
x = [[11, 22], [39, 0], [33, 39], [1, 28], [9, 24], [19, 14], [6, 7], [28, 3], [4, 17], [35, 15]]

In [54]:
import numpy as np
def logloss(z, y_true, x):
    '''z, y_true and x are lists
       output -> Two numpy arrays are expected to be returned'''
    
    z = np.asarray(z)
    y_true = np.asarray(y_true)
    x = np.asarray(x)
    
    # YOUR CODE GOES HERE

    y_hat = 1 / (1 + (np.exp(-z)))
    #y_hat = y_hat.round(2)

    logloss = (-1 * y_true * np.log(y_hat)) - ((1 - y_true) * np.log(1 - y_hat))
    logloss = logloss.round(2)
    
    logloss_dev = (y_hat - y_true) * [x[0] for x in x]
    logloss_dev = logloss_dev.round(2)

    return logloss,logloss_dev



logloss(z, y_true, x)

(array([0.04, 0.73, 0.38, 5.98, 3.1 , 0.75, 0.  , 0.17, 1.91, 0.19]),
 array([ -0.47,  20.28, -10.52,   1.  ,   8.59,  10.07,  -0.  ,  -4.36,
          3.41,  -6.18]))

In [53]:
[x[0] for x in x]

[11, 39, 33, 1, 9, 19, 6, 28, 4, 35]

In [55]:
x[:,0]

TypeError: list indices must be integers or slices, not tuple

**Problem Description**

Given train and test data in the form of lists as arguments of the function errors(), complete the function to return the lists train_errs and test_errs where train_err will consist of the errors in X_train for different values of C in the list c, and test_errs will have the errors for the test data.
 - ***C is basically a hyperparameter in the logistic regression model representing the reciprocal of regularization parameter λ. High values of C cause less regularization which leads the model to overfit on training data, whereas low values of C causes it to underfit.***

Note: Here, by error we mean the percentage of misclassified points, converted to decimal.


Sample Input:

- X_train = [[93, 17], [83, 8], [80, 13], [15, 30], [63, 31], [11, 28], [73, 55], [82, 11], [50, 6], [2, 89]]
- y_train = [0, 0, 1, 0, 1, 1, 1, 1, 0, 1]
- X_test = [[9, 53], [6, 7], [21, 61], [65, 75], [48, 67]]
- y_test = [0, 0, 1, 0, 0]
- c = [0.001, 0.01, 0.1, 1, 10, 100, 1000]


Sample Output:

- train_errs = [0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
- test_errs = [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]

In [74]:
import numpy as np

#import logistic regression
from sklearn.linear_model import LogisticRegression

def training_errors(X_train, y_train, X_test, y_test,c):
    ''' X_train, y_train, X_test, y_test,c are all in the form of lists
        Output -> Two lists are expected to be returned'''
    
    #converting all the lists into Numpy arrays
    X_train = np.asarray(X_train)  
    X_test = np.asarray(X_test)  
    y_train = np.asarray(y_train)  
    y_test = np.asarray(y_test)  
    train_errs = list()
    test_errs = list()
    
    for c_value in c:
        #initialize the logistic regression model
        clf = LogisticRegression(C=c_value)
        
        #fit the training data on the model
        clf.fit(X_train,y_train)

        #y_pred_train = clf.predict(X_train)
        train_score = clf.score(X_train,y_train)
        test_score = clf.score(X_test,y_test)
        
        #append the errors for each value of C for train and test data.
        train_errs.append(round( 1.0 - train_score, 2))
        test_errs.append(round( 1.0 - test_score,2))
    
    return train_errs,test_errs

In [75]:
X_train = [[44, 15],[75, 17],[30, 50],[41, 89],[15,3],[36,  7],[46, 22],[96, 13],[85,  5],[81, 35]]
y_train = [1, 1, 1, 0, 1, 1, 0, 1, 0, 0]
X_test = [[61, 64],[40, 91],[67, 22],[81, 13],[50, 85],[30, 49],[35, 10],[49, 76],[50, 65],[56,  2]]
y_test = [0, 1, 0, 0, 1, 0, 0, 0, 0, 1]
c = [0.001, 0.01, 0.1, 1, 10, 100, 1000]


training_errors(X_train, y_train, X_test, y_test,c)

([0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3], [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6])