In [1]:
import numpy as np

In [2]:
def Ver001(x):
    return [1/(1 + np.exp(-ele)) for ele in x]

def Ver002(x):
    return 1 / (1 + (np.exp(-x)))

min_limit = 709
def Ver003(x):
    return 1 / (1 + np.exp(-(np.clip(x,-min_limit,None))))

In [5]:
Ver001([1])

[0.7310585786300049]

In [8]:
Ver002(1)

0.7310585786300049

In [7]:
Ver003([1])

array([0.73105858])

Convert a given numpy array to its sigmoid and its associated derivative

In [2]:
# input array
x = [[3, 1], [0, 4]] 

#Sample output
# [[0.95 0.73]
#  [0.5 0.98]] 
# [[0.05 0.2 ]
#  [0.25 0.02]]

In [15]:
import numpy as np

def sigmoid(x):
    '''x is a list
       Output -> Two numpy arrays are expected to be returned both with the same dimensions as of x'''
    
    x = np.asarray(x)

    sigmoid  = 1 / (1 + (np.exp(-x)))
    sigmoid_dev = sigmoid * (1 - sigmoid)
    print(sigmoid.round(2))
    print(sigmoid_dev.round(2))
           
#Driver function
sigmoid(x)

[[0.95 0.73]
 [0.5  0.98]]
[[0.05 0.2 ]
 [0.25 0.02]]
