In [1]:
import numpy as np

In [2]:
def Ver001(x):
    return [1/(1 + np.exp(-ele)) for ele in x]

def Ver002(x):
    return 1 / (1 + (np.exp(-x)))

min_limit = 709
def Ver003(x):
    return 1 / (1 + np.exp(-(np.clip(x,-min_limit,None))))

In [5]:
Ver001([1])

[0.7310585786300049]

In [8]:
Ver002(1)

0.7310585786300049

In [7]:
Ver003([1])

array([0.73105858])

Convert a given numpy array to its sigmoid and its associated derivative

In [24]:
# input array
x = [[3, 1], [0, 4]] 

#Sample output
# [[0.95 0.73]
#  [0.5 0.98]] 
# [[0.05 0.2 ]
#  [0.25 0.02]]

In [25]:
import numpy as np
import warnings as war
war.filterwarnings('ignore')

def sigmoid(x):
    '''x is a list
       Output -> Two numpy arrays are expected to be returned both with the same dimensions as of x'''
    
    x = np.asarray(x)

    sigmoid  = 1 / (1 + (np.exp(-x)))
    sigmoid_dev = sigmoid * (1 - sigmoid)
    print(sigmoid.round(2))
    print(sigmoid_dev.round(2))
           
#Driver function
sigmoid(x)

[[0.95 0.73]
 [0.5  0.98]]
[[0.05 0.2 ]
 [0.25 0.02]]


Q) Log loss and derivative

In [26]:
# input
z = [3.11, 0.08, 0.76, 5.98, 3.05, 0.12, 8.99, 1.69, 1.75, 1.54] 
y_true = [1, 0, 1, 0, 0, 0, 1, 1, 0, 1]  
x = [[11, 22], [39, 0], [33, 39], [1, 28], [9, 24], [19, 14], [6, 7], [28, 3], [4, 17], [35, 15]]

In [54]:
import numpy as np
def logloss(z, y_true, x):
    '''z, y_true and x are lists
       output -> Two numpy arrays are expected to be returned'''
    
    z = np.asarray(z)
    y_true = np.asarray(y_true)
    x = np.asarray(x)
    
    # YOUR CODE GOES HERE

    y_hat = 1 / (1 + (np.exp(-z)))
    #y_hat = y_hat.round(2)

    logloss = (-1 * y_true * np.log(y_hat)) - ((1 - y_true) * np.log(1 - y_hat))
    logloss = logloss.round(2)
    
    logloss_dev = (y_hat - y_true) * [x[0] for x in x]
    logloss_dev = logloss_dev.round(2)

    return logloss,logloss_dev



logloss(z, y_true, x)

(array([0.04, 0.73, 0.38, 5.98, 3.1 , 0.75, 0.  , 0.17, 1.91, 0.19]),
 array([ -0.47,  20.28, -10.52,   1.  ,   8.59,  10.07,  -0.  ,  -4.36,
          3.41,  -6.18]))

In [53]:
[x[0] for x in x]

[11, 39, 33, 1, 9, 19, 6, 28, 4, 35]

In [55]:
x[:,0]

TypeError: list indices must be integers or slices, not tuple